<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
        <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'" >
        <PackageReference Include="System.Memory" Version="4.6.3" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Resources\resources.zip"/>
    </ItemGroup>
</Project>