# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore Source
    - name: Build
      run: dotnet build Source --no-restore
    - name: Test
      run: dotnet test Source --no-build --verbosity normal
    - name: Deploy
      run: dotnet publish -c Release -f net10.0 -o ./../Deploy ./Lyon/Lyon.csproj
      working-directory: Source
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: Deploy
